- hosts: all
  vars:
    vagrant_plugins_user: vagrant
    vagrant_plugins:
      - name: vagrant-digitalocean
      - name: nugrant
  tasks:
    - name: installs rsync
      yum: name=rsync
  roles:
    - rfhayashi.vagrant