Vagrant.configure('2') do |config|
  config.vm.box = 'digital_ocean'
  config.vm.box_url = 'https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box'

  config.ssh.private_key_path = '~/.ssh/id_rsa'

  config.vm.synced_folder '.', '/vagrant', type: 'rsync'

  config.vm.provider :digital_ocean do |provider, override|
    override.nfs.functional = false
    provider.token = config.user.digital_ocean_token
    provider.image = 'centos-7-x64'
    provider.region = 'nyc1'
  end

  config.vm.provision 'ansible_local' do |a|
    a.playbook = 'vagrant.yml'
    a.galaxy_role_file = 'requirements.yml'
    a.verbose = 'vv'
  end
end